name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-node:
    name: Test on Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x # to be removed 2025-04-30
          - 20.x # to be removed 2026-04-30
          - 21.x # to be removed 2024-06-01
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Run Node.js Tests
        run: npm test
