# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npm test

  package:
    name: Package
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - run: npm ci
      - run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version
      - run: npm run build
      - run: npm pack

      - name: Package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.tgz"
          if-no-files-found: error

  publish:
    name: Publish to NPM
    if: success('build') && success('package')
    needs: [package]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - run: npm publish --access public *.tgz
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
